# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Yada-Yada-Yada
version:      1.00
version_from: Yada.pm
installdirs:  site
requires:
    Filter::Simple:                0.76
    Test::Simple:                  0.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
